### ISSUE TITLE
explain please

### ISSUE THREAD

**Issue by ronenpi18** [Junlin-Yin/retiming-composite#1]
hey,
i see you have three different projects here on GitHub, that concern the same purpose.. 
i am very interested about it. 
can you explain more about your project and show some results? 
thanks

**Comment by Junlin-Yin** [comment]
hello,
I did once create three different projects here, and they are all about speech-driven video synthesis.
You can just access my repo named audio2video-v1, which contains the whole pipeline of this task.
As for the results, I generated one but it seems not good with the lack of temporal smoothness. Anyway, I'll still show my results if you are interested : )

**Comment by ronenpi18** [comment]
yes! I'd love that! very much! 
I'll check out your new repo.. 
what do you mean at "temporal smoothness."? what data did you used to train the model? perhaps the algorithm wasn't fine-tuned ?

**Comment by Junlin-Yin** [comment]
I'm so glad that you wanna know more about my project! thx!
the lack of temporal smoothness here means that most of frames of output video STATICALLY seems natural and photo-realistic, but when playing the video you'll see some flickers or jitters around the mouth region. the problem comes out DYNAMICALLY, and it may result from the algorithm i chose, not the parameter tuning.
i'll upload the final result and update README.md with more details in my new repo. if you still have some questions after referring to these files, don't hesitate to ask me!

**Comment by ronenpi18** [comment]
awesome !! I'm thrilled to read your README .. 
would you explain there how to run the project?
I think I have some ideas, I'll create pull requests to your repo :)

**Comment by Junlin-Yin** [comment]
current codes are a little unfriendly for interaction. let me do some modifications and specify how to run my codes in README.. sorry for letting you waiting for some time
i'll highly appreciate it if you can add your ideas to this project! i'm looking forward to it very much!

**Comment by Junlin-Yin** [comment]
ok now it's done. you can have a try. if you find some bugs, please tell me : )
